"""Per-format handler stubs for ``Spectrum`` load/save (FR-132..FR-134).

Each function corresponds to one ``handler=`` named in a ``LoadSpectrum`` /
``SaveSpectrum`` ``FormatCapability`` record (spec §"Spectrum load/save
capabilities"). The block methods delegate here; implementers fill the bodies.

Loaders return a single :class:`Spectrum` built via
``_support.build_spectrum``. Savers write *spectrum* to *path* and return
``None``. Heavy/optional parsers (scipy, vendor SDKs) must be lazy-imported
inside the function body, never at module top level.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from scistudio_blocks_spectroscopy.types import Spectrum

# --------------------------------------------------------------------------
# Delimited text + workbook + native + standard interchange (load + save)
# --------------------------------------------------------------------------


def load_delimited_text(path: Path, **kwargs: Any) -> Spectrum:
    """Load a ``.txt``/``.csv``/``.tsv`` two-column spectrum.

    Implementation plan (FR-132, FR-142):
      1. Sniff delimiter from suffix (txt/space, csv/comma, tsv/tab) or content.
      2. Read two numeric columns -> (lambda, intensity); skip header/comments.
      3. Build via _support.build_spectrum(lam, inten, meta=Spectrum.Meta(
         source_file=str(path))); spectrum_id stays None (generated by loader).
    Edge cases: ragged rows; non-numeric header; empty file; single column.
    Test plan: test_spectrum_io.py::test_load_delimited_text_roundtrip,
      ::test_load_delimited_text_rejects_single_column.
    """
    raise NotImplementedError("skeleton — implement per FR-132/FR-142 (delimited text load); see comment above")


def save_delimited_text(spectrum: Spectrum, path: Path, **kwargs: Any) -> None:
    """Save a spectrum as ``.txt``/``.csv``/``.tsv`` two columns.

    Implementation plan (FR-132, FR-037):
      1. lam, inten = _support.spectrum_arrays(spectrum).
      2. Pick delimiter from path suffix; write "lambda<delim>intensity" rows.
      3. metadata_fidelity is pixel_only — do not write typed meta.
    Edge cases: parent dir missing (mkdir); zero-length spectrum.
    Test plan: test_spectrum_io.py::test_save_delimited_text_writes_two_columns.
    """
    raise NotImplementedError("skeleton — implement per FR-132/FR-037 (delimited text save); see comment above")


def load_spectrum_xlsx(path: Path, **kwargs: Any) -> Spectrum:
    """Load a single spectrum from an ``.xlsx``/``.xls`` workbook.

    Implementation plan (FR-132, FR-142):
      1. Lazy-import the workbook reader (openpyxl/pandas) inside this body.
      2. Read the spectrum sheet's lambda/intensity columns + typed-meta cells
         (lambda_unit, intensity_unit, lambda_kind, modality).
      3. Build via _support.build_spectrum with a populated Spectrum.Meta.
    Edge cases: multiple sheets; missing meta cells; merged headers.
    Test plan: test_spectrum_io.py::test_load_spectrum_xlsx_reads_typed_meta.
    """
    raise NotImplementedError("skeleton — implement per FR-132 (xlsx spectrum load); see comment above")


def save_spectrum_xlsx(spectrum: Spectrum, path: Path, **kwargs: Any) -> None:
    """Save a single spectrum to an ``.xlsx`` workbook with typed meta.

    Implementation plan (FR-132, FR-037):
      1. Lazy-import the workbook writer inside this body.
      2. Write lambda/intensity rows plus typed-meta cells (lambda_unit,
         intensity_unit, lambda_kind, modality) — typed_meta fidelity.
    Edge cases: meta=None; parent dir missing.
    Test plan: test_spectrum_io.py::test_save_spectrum_xlsx_roundtrips_typed_meta.
    """
    raise NotImplementedError("skeleton — implement per FR-132 (xlsx spectrum save); see comment above")


def load_spectrum_json(path: Path, **kwargs: Any) -> Spectrum:
    """Load the package-native ``.spectrum.json`` format (lossless).

    Implementation plan (FR-132, FR-141):
      1. json.loads(path.read_text()); read lambda[], intensity[], and the
         full typed Spectrum.Meta (lambda_unit, intensity_unit, lambda_kind,
         modality) plus spectrum_id/user.
      2. Build via _support.build_spectrum with reconstructed Meta + user.
    Edge cases: schema-version mismatch; missing arrays; extra unknown keys.
    Test plan: test_spectrum_io.py::test_spectrum_json_lossless_roundtrip.
    """
    raise NotImplementedError("skeleton — implement per FR-132/FR-141 (spectrum_json load); see comment above")


def save_spectrum_json(spectrum: Spectrum, path: Path, **kwargs: Any) -> None:
    """Save the package-native ``.spectrum.json`` format (lossless).

    Implementation plan (FR-132, FR-141):
      1. lam, inten = _support.spectrum_arrays(spectrum).
      2. Serialise {lambda, intensity, meta:{lambda_unit,...}, user, schema}.
    Edge cases: non-JSON-serialisable user values; meta=None.
    Test plan: test_spectrum_io.py::test_spectrum_json_lossless_roundtrip.
    """
    raise NotImplementedError("skeleton — implement per FR-132/FR-141 (spectrum_json save); see comment above")


def load_jcamp_dx(path: Path, **kwargs: Any) -> Spectrum:
    """Load a JCAMP-DX (``.jdx``/``.dx``/``.jcamp``) spectrum.

    Implementation plan (FR-132, FR-142):
      1. Parse JCAMP-DX header (##XUNITS, ##YUNITS, ##XYDATA / (X++(Y..Y))).
      2. Decompress the compressed-form ASCII data into lambda/intensity.
      3. Map XUNITS/YUNITS -> Spectrum.Meta.lambda_unit/intensity_unit.
    Edge cases: AFFN vs PAC/SQZ/DIF encodings; multi-block files (first block).
    Test plan: test_spectrum_io.py::test_load_jcamp_dx_decodes_xydata.
    """
    raise NotImplementedError("skeleton — implement per FR-132 (jcamp_dx load); see comment above")


def save_jcamp_dx(spectrum: Spectrum, path: Path, **kwargs: Any) -> None:
    """Save a spectrum as JCAMP-DX (``.jdx``/``.dx``/``.jcamp``).

    Implementation plan (FR-132):
      1. Emit required ##TITLE/##JCAMP-DX/##XUNITS/##YUNITS headers from meta.
      2. Write XYDATA=(XY..XY) AFFN block; ##END.
    Edge cases: missing units -> default labels; very large point counts.
    Test plan: test_spectrum_io.py::test_save_jcamp_dx_writes_valid_header.
    """
    raise NotImplementedError("skeleton — implement per FR-132 (jcamp_dx save); see comment above")


def load_spc(path: Path, **kwargs: Any) -> Spectrum:
    """Load a Galactic/Thermo SPC (``.spc``) single spectrum.

    Implementation plan (FR-132, FR-138):
      1. Lazy-import / hand-parse the SPC binary header + subfile.
      2. Build lambda from the x-axis (or evenly spaced first/last) + y data.
      3. Map fxtype/fytype -> Spectrum.Meta.lambda_kind/units.
    Edge cases: multifile SPC (return first sub); old vs new SPC format flag.
    Test plan: test_spectrum_io.py::test_load_spc_single_spectrum.
    """
    raise NotImplementedError("skeleton — implement per FR-132/FR-138 (spc load); see comment above")


def save_spc(spectrum: Spectrum, path: Path, **kwargs: Any) -> None:
    """Save a spectrum as SPC (``.spc``) single subfile.

    Implementation plan (FR-132, FR-138):
      1. lam, inten = _support.spectrum_arrays(spectrum).
      2. Write an SPC header (evenly-spaced or x-y) + one subfile.
    Edge cases: non-monotonic lambda; unit flags.
    Test plan: test_spectrum_io.py::test_save_spc_single_spectrum.
    """
    raise NotImplementedError("skeleton — implement per FR-132/FR-138 (spc save); see comment above")


# --------------------------------------------------------------------------
# Vendor / instrument-native LOAD-ONLY formats (FR-133, FR-140)
# --------------------------------------------------------------------------


def load_thermo_omnic_spa(path: Path, **kwargs: Any) -> Spectrum:
    """Load a Thermo OMNIC ``.spa`` single spectrum (load-only).

    Implementation plan (FR-133, FR-140):
      1. Parse the SPA binary header for spectrum offset, point count, range.
      2. Read float intensities; reconstruct lambda from first/last/spacing.
    Edge cases: interferogram vs processed block selection; endianness.
    Test plan: test_spectrum_io.py::test_load_thermo_omnic_spa.
    """
    raise NotImplementedError("skeleton — implement per FR-133 (thermo_omnic_spa load); see comment above")


def load_bruker_opus(path: Path, **kwargs: Any) -> Spectrum:
    """Load a Bruker OPUS (``.opus``) single spectrum (load-only).

    Implementation plan (FR-133, FR-140):
      1. Parse OPUS block directory; locate AB/absorbance data + parameter block.
      2. Build lambda from FXV/LXV/NPT; map DXU -> lambda_unit.
    Edge cases: extensionless OPUS via explicit capability_id; multiple data blocks.
    Test plan: test_spectrum_io.py::test_load_bruker_opus.
    """
    raise NotImplementedError("skeleton — implement per FR-133 (bruker_opus load); see comment above")


def load_horiba_labspec(path: Path, **kwargs: Any) -> Spectrum:
    """Load a HORIBA LabSpec single-spectrum export (load-only).

    Implementation plan (FR-133, FR-140):
      1. Detect l6s/l5s/ngs/xml flavour; parse coordinate + intensity arrays.
      2. Map LabSpec axis tags -> Spectrum.Meta.lambda_kind/units.
    Edge cases: xml transfer profile vs binary; map exports (dataset handler).
    Test plan: test_spectrum_io.py::test_load_horiba_labspec.
    """
    raise NotImplementedError("skeleton — implement per FR-133 (horiba_labspec load); see comment above")


def load_renishaw_wdf(path: Path, **kwargs: Any) -> Spectrum:
    """Load a Renishaw WiRE ``.wdf`` single spectrum (load-only).

    Implementation plan (FR-133, FR-140):
      1. Parse WDF block structure (WDF1/DATA/XLST); read xlist + one spectrum.
      2. Map XLST type -> lambda_kind (Raman shift / wavelength).
    Edge cases: map files contain many spectra -> dataset handler instead.
    Test plan: test_spectrum_io.py::test_load_renishaw_wdf_single.
    """
    raise NotImplementedError("skeleton — implement per FR-133 (renishaw_wdf load); see comment above")


def load_andor_solis(path: Path, **kwargs: Any) -> Spectrum:
    """Load an Andor Solis (``.sif``/``.fits``/``.fit``/``.asc``) spectrum (load-only).

    Implementation plan (FR-133, FR-140):
      1. Branch on suffix: SIF binary, FITS (lazy astropy/np), or ASCII.
      2. Extract 1-D spectrum + wavelength calibration if present.
    Edge cases: 2-D frames -> collapse/select row; missing calibration.
    Test plan: test_spectrum_io.py::test_load_andor_solis_ascii.
    """
    raise NotImplementedError("skeleton — implement per FR-133 (andor_solis load); see comment above")


def load_princeton_spe(path: Path, **kwargs: Any) -> Spectrum:
    """Load a Princeton/LightField ``.spe`` single spectrum (load-only).

    Implementation plan (FR-133, FR-140):
      1. Detect SPE v2.x header vs v3.0 XML footer; read frame data.
      2. Reduce to one spectrum; read wavelength calibration from footer.
    Edge cases: multi-frame SPE (return first / configured frame); ROI handling.
    Test plan: test_spectrum_io.py::test_load_princeton_spe_single.
    """
    raise NotImplementedError("skeleton — implement per FR-133 (princeton_spe load); see comment above")


__all__ = [
    "load_andor_solis",
    "load_bruker_opus",
    "load_delimited_text",
    "load_horiba_labspec",
    "load_jcamp_dx",
    "load_princeton_spe",
    "load_renishaw_wdf",
    "load_spc",
    "load_spectrum_json",
    "load_spectrum_xlsx",
    "load_thermo_omnic_spa",
    "save_delimited_text",
    "save_jcamp_dx",
    "save_spc",
    "save_spectrum_json",
    "save_spectrum_xlsx",
]
